# Generated by Django 3.2.5 on 2024-06-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='number_plate',
            field=models.CharField(default='UNKNOWN', max_length=50, unique=True),
        ),
    ]
