# Generated by Django 3.2.5 on 2024-06-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240627_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_plate',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
    ]
