# Generated by Django 3.2.5 on 2024-07-04 03:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_reservation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 4, 4, 52, 29, 301908, tzinfo=utc), null=True),
        ),
    ]
