# Generated by Django 3.2.5 on 2024-06-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_number_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number_plate',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
