# Generated by Django 3.2.5 on 2024-06-27 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_reservation_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_code',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
